### ISSUE TITLE
[Request]: Better ASI Handling

### ISSUE THREAD

**Issue by Clone69420** [TupoyeMenu/TupoyeMenu#27]
### Problem

Many ASI Scripts are not Supported but if they load and u unload the menu and reinject the menu crashes. Also unload an ASI while the Menu is still injected would be an good idea

### Solution

Better Patching of PE Image. Or just use a custom ScriptHookV.dll for better experience..

### Reason

Fixes many named ASI Problems

### Additional context

- None

**Comment by tupoy-ya** [comment]
Can you please link me some open source ASI Scripts that don't work. Because i stopped playing with ASI mods right now, and the only one i know that doesn't work is https://www.gta5-mods.com/scripts/script-viewer.

> Many ASI Scripts are not Supported but if they load and u unload the menu and reinject the menu crashes.

Probably a problem with ASI Script itself not the ASI Loader.

> Or just use a custom ScriptHookV.dll for better experience..

Well i can remove this scripthook then.

**Comment by Clone69420** [comment]
> Can you please link me some open source ASI Scripts that don't work. Because i stopped playing with ASI mods right now, and the only one i know that doesn't work is https://www.gta5-mods.com/scripts/script-viewer.
> 
> > Many ASI Scripts are not Supported but if they load and u unload the menu and reinject the menu crashes.
> 
> Probably a problem with ASI Script itself not the ASI Loader.
> 
> > Or just use a custom ScriptHookV.dll for better experience..
> 
> Well i can remove this scripthook then.

An good example is Chaos Mod [ this asi loader no | with cherax asi loader yes ]
Source:
https://github.com/gta-chaos-mod/ChaosModV

**Comment by tupoy-ya** [comment]
> An good example is Chaos Mod [ this asi loader no | with cherax asi loader yes ] Source: https://github.com/gta-chaos-mod/ChaosModV

Hmm last time i used it was at https://github.com/gta-chaos-mod/ChaosModV/commit/5b53a8d2cd01fdc17767dcf2186eec99bb2fb7e7 and it worked fine but now it doesn't.

**Comment by tupoy-ya** [comment]
> I'm sorry for the stupid question lads but I'm surprised a free menu has an ASI Loader! I'm interested in loading up some visual and performance mods with Tupoye, and I'm not sure exactly how to do that. Can I ask for some instructions (or if I have to build it myself since I see something about having to enable it in cmake) as to how to use it? Thanks in advance!

You need to put your asi plugins into `%appdata%/TupoyeMenu/OpenHookV/` through the ScriptHook API is not complete and some mods will not work.

Also keep in mind that TupoyeMenu does nothing to prevent Asi mods from being detected, for example Menyoo has an old detected vehicle spawn bypass for multiplayer in it.

I'm not even sure if this Script Hook still works as i very rarely use it, mostly with my Menyoo fork, for which it worked fine the last time i tested it.

**Comment by DavidScann** [comment]
> ly w

Thank you! I doubt that my mods will trigger any detections, as they're just visual. Thank you so much!

**Comment by tupoy-ya** [comment]
TupoyeMenu no longer supports ASI Loading and the ScriptHookV API, due to YimMenu changing the invoker logic.
