### ISSUE TITLE
[Bug]: CMake Error

### ISSUE THREAD

**Issue by DatPizzaGuy** [TupoyeMenu/TupoyeMenu#38]
### Describe the bug

Can't Generate/Clone Project 

### Expected Behavior

Tired Following The Steps To Get the Project to load into Visual Studios Even Tried Google To Find a Solution With No Luck

### Screenshots and/or Logs

```
Severity Code Description Project	File	Line	Suppression State
Error CMake Error at F:/Visual Studios/VS IDE/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1589 (message):
  CMake step for minhook failed: 1	CrossCompileExample	F:/Visual Studios/VS IDE/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/FetchContent.cmake 1589	
  
  and this one 
Severity	Code Description	Project	File	Line	Suppression State
Error CMake Error at F:/Visual Studios/VS IDE/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/ExternalProject.cmake:2786 (message):
  error: could not find git for clone of minhook-populate F:/Visual Studios/VS IDE/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.24/Modules/ExternalProject.cmake	2786
```
 

### Build

- [X] This does not occur on unmodified YimMenu

**Comment by tupoy-ya** [comment]
Do you have git installed?

**Comment by DatPizzaGuy** [comment]
yes i have git installed and cmake installed and also Visual Studios has Cmake Installed from its list of stuff

**Comment by tupoy-ya** [comment]
Does this occur on unmodified YimMenu?

**Comment by DatPizzaGuy** [comment]
sorry i see i clicked this does not tbh didn't have my glasses on.... i started by trying yours and got that error and i tried using unmodified YimMenu and it still gives me the same error

**Comment by DatPizzaGuy** [comment]
still doesn't work even tried reinstalling VS but that didn't fix it

**Comment by tupoy-ya** [comment]
Is git available in normal cmd?

**Comment by DatPizzaGuy** [comment]
yes it is and yes it seems related but i already tried reinstalling and still same 2 errors

**Comment by tupoy-ya** [comment]
Does it work if you manually generate cmake files using:
```bash
mkdir build
cd build
cmake ..
```
?

**Comment by DatPizzaGuy** [comment]
$ cmake ..
CMake Warning:
  Ignoring extra path from command line:

   ".."


CMake Error: The source directory  does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

but the CmakeLists.txt is there from the git pull

**Comment by DatPizzaGuy** [comment]
i reinstalled cmake and now while in cd build i get  Permission denied on like everything that comes up 
find: ‘/c/Windows/appcompat/Programs’: Permission denied
find: ‘/c/Windows/LiveKernelReports’: Permission denied
find: ‘/c/Windows/Logs/HomeGroup’: Permission denied
find: ‘/c/Windows/Logs/SystemRestore’: Permission denied
find: ‘/c/Windows/Logs/Telephony’: Permission denied
find: ‘/c/Windows/Minidump’: Permission denied
find: ‘/c/Windows/ModemLogs’: Permission denied
find: ‘/c/Windows/Prefetch’: Permission denied
find: ‘/c/Windows/Provisioning/Autopilot’: Permission denied
find: ‘/c/Windows/Resources/Themes/aero/VSCache’: Permission denied
find: ‘/c/Windows/security/audit’: Permission denied
find: ‘/c/Windows/security/cap’: Permission denied
find: ‘/c/Windows/ServiceProfiles/LocalService’: Permission denied
find: ‘/c/Windows/ServiceProfiles/NetworkService’: Permission denied
find: ‘/c/Windows/ServiceState’: Permission denied

**Comment by tupoy-ya** [comment]
That looks weird why does try to find this directories in `C:/Windows`

**Comment by DatPizzaGuy** [comment]
im using an external HDD to do this i run most my stuff on there including VS

**Comment by DatPizzaGuy** [comment]
and when i go to the TupoyeMenu i try right clicking the folder and opening it with VS and i get the Original error i started with

**Comment by tupoy-ya** [comment]
The original error is VS not being able to find your `git` binary, is it in the PATH?

> i reinstalled cmake and now while in cd build i get Permission denied on like everything that comes up
```
find: ‘/c/Windows/appcompat/Programs’: Permission denied
find: ‘/c/Windows/LiveKernelReports’: Permission denied
find: ‘/c/Windows/Logs/HomeGroup’: Permission denied
find: ‘/c/Windows/Logs/SystemRestore’: Permission denied
find: ‘/c/Windows/Logs/Telephony’: Permission denied
find: ‘/c/Windows/Minidump’: Permission denied
find: ‘/c/Windows/ModemLogs’: Permission denied
find: ‘/c/Windows/Prefetch’: Permission denied
find: ‘/c/Windows/Provisioning/Autopilot’: Permission denied
find: ‘/c/Windows/Resources/Themes/aero/VSCache’: Permission denied
find: ‘/c/Windows/security/audit’: Permission denied
find: ‘/c/Windows/security/cap’: Permission denied
find: ‘/c/Windows/ServiceProfiles/LocalService’: Permission denied
find: ‘/c/Windows/ServiceProfiles/NetworkService’: Permission denied
find: ‘/c/Windows/ServiceState’: Permission denied
```

I think your cmake install is broken or i just don't know how cmake works on windows.

**Comment by DatPizzaGuy** [comment]
i have git installed on the same external HDD as well 
also tried installing it on my C drive still same issues but i liked the premake5 way of doing the setup worked no issues 
but to each their own.. thanks for trying to help prob wont be able to fix this lol

**Comment by DatPizzaGuy** [comment]
ik menus are down an what not from GTA updating but i tried using my laptop it seemed to work still got that permission denied errors when doing Git Bash but  i tried opening the folder in VS and Cmake finished no errors but never gave me an .sln file not sure what im doing wrong

**Comment by tupoy-ya** [comment]
> ik menus are down an what not from GTA updating but i tried using my laptop it seemed to work still got that permission denied errors when doing Git Bash but i tried opening the folder in VS and Cmake finished no errors but never gave me an .sln file not sure what im doing wrong

VS open cmake folder feature doesn't generate sln as far as i know, to generate sln you need to manually run `cmake ..` in `cmd`

**Comment by tupoy-ya** [comment]
Unrelated to TupoyeMenu.
