### ISSUE TITLE
Hello dear stranger

### ISSUE THREAD

**Issue by iswaxan** [TupoyeMenu/TupoyeMenu#59]
A man stole your menu, just renaming it as "reverie" and says he made the mod menu, here some screenshots![image](https://user-images.githubusercontent.com/78171263/233868236-c20156e4-5173-4452-a078-08d907075fdb.png) ![image](https://user-images.githubusercontent.com/78171263/233868244-c3229499-968b-4643-9dca-0e9bdf8c0a93.jpeg) if you want the discord here it is: https://discord.gg/kanjishere

**Comment by iswaxan** [comment]
Sorry for bad quality but it's in the discord tho

**Comment by tupoy-ya** [comment]
Not much i can do with it.
How do you even find such discord menus?

**Comment by tupoy-ya** [comment]
Made an issue asking him to open source the menu or take it down: https://github.com/whoskanji/ReverieYUHR/issues/1

But i'm pretty sure i will have to make TupoyeMenu plant based instead.

**Comment by iswaxan** [comment]
> Made an issue asking him to open source the menu or take it down: https://github.com/whoskanji/ReverieYUHR/issues/1
> 
> 
> 
> But i'm pretty sure i will have to make TupoyeMenu plant based instead.

What does it means "plant based" ?

**Comment by iswaxan** [comment]
and also, what decompiler ya using ? or just how ya decoded da dll ?

**Comment by tupoy-ya** [comment]
> What decompiler ya using ? or just how ya decoded da dll ?

I just opened the DLL in a hex editor, if you want the name it's "Okteta" running on KDE.

> What does it mean "plant based" ?

I explained in their discard before they deleted my message and banned me.
Now just wait until i make TupoyeMenu plant based as well.

**Comment by iswaxan** [comment]
> I just opened the DLL in a hex editor

does this for me https://cdn.discordapp.com/attachments/906597924622970911/1100730155430842500/Desktop_Screenshot_2023.04.26_-_12.26.37.38.png

**Comment by iswaxan** [comment]
even on text viewer

**Comment by iswaxan** [comment]
> #### Stop spamming them it won't help anyone.
> 
> 
> 
> > does this for me https://cdn.discordapp.com/attachments/906597924622970911/1100730155430842500/Desktop_Screenshot_2023.04.26_-_12.26.37.38.png
> 
> 
> 
> Have you tried searching in the file?
> 
> 
> 
> As for decompiling the menu you can use Ghidra and load TupoyeMenu pdb, not sure why you would need to do that through.
> 
> 
> 
> 

Ok ima stop spammin em, but yeah ima try

**Comment by iswaxan** [comment]
You made the menu plant based ? (Still don't know what it means tho)

**Comment by tupoy-ya** [comment]
Not yet, need to finish my OpenVHook update first.

**Comment by iswaxan** [comment]
Did he just deleted yer issue ?

**Comment by tupoy-ya** [comment]
TupoyeMenu is currently partially plant based.

**Comment by SlavicBlin** [comment]
> TupoyeMenu is currently partially plant based.

Menu becoming vegan
