### ISSUE TITLE
[Request]: macOS crossover 

### ISSUE THREAD

**Issue by Hakimbhb** [TupoyeMenu/TupoyeMenu#60]
### Problem

i can t use neither yimmenu on crossover i m macOS user and same problem with ur menu modified
it crush the game!! with no prompt even the terminal it just crush!!

could u try to figure a solution?

i didn't t found even log file to send u 

### Solution

idk but i m thinking that's bcs it didn't generate the file inside the C or the game folder i m asking to be a betta user if ur interested 

idk how the dll work but that's maybe it have direct to generate like c:/yimmennu 
wich is not working in crossover bcs it should be 
`im not sure but this is the path and idk how the dll work..`
/crossover/c:/newfile...

### Reason

 i m not even sure lol just a guess!

bcs when i open c or game folder there is no folder generated for ur mod menu in other hand  i could see scooby or the menu that's worked for me!

### Additional context

i m using this mod menu work perfectly for me maybe it help u more

https://github.com/HatchesPls/GrandTheftAutoV-Cheat

for yimmenu it start the terminal i create an issue maybe it help u too!

https://github.com/YimMenu/YimMenu/issues/1307

- [x ] thank you for ur time and i wish u consider my request !

**Comment by tupoy-ya** [comment]
1. Please show some respect and write in English if you can.
2. Don't use MacOS.
3. If the problem exists on YimMenu don't ask for help here.
4. Both YimMenu and TupoyeMenu work fine on GNU Linux with Wine which as far as i know crossover is based on, so just don't use crossover and use plain wine.
5. If you are co-loading another menu no help will be provided.
6. Crashing is a bug so you should have used a bug template.

**Comment by Hakimbhb** [comment]
1. i m sorry if u read it as disrespect i didn't t mean it!
2. my english is not my first language so sorry for that an i tried to explain it
3. i was just requesting bcs i saw u some modification just requesting if that could be doing by u 
4. the menu i use it was my purpose for it maybe it help u to fix the crash!
5. thank you for your time and i m sorry another time if u read it as disrespect
`u already help me thank you ..`
