### ISSUE TITLE
[Bug]: Invalid sector position

### ISSUE THREAD

**Issue by SylveonDeko** [TupoyeMenu/TupoyeMenu#73]
### Describe the bug

Console and in game alerts are spammed with this when joining an online session

### Screenshots and/or Logs

![image](https://github.com/TupoyeMenu/TupoyeMenu/assets/59923820/2eb2905d-e7ff-4858-b75b-017b6e317139)

### Store

None

### Build

- [X] I've confirmed the issue exists on the latest version of TupoyeMenu and does not exist on the latest version of YimMenu

**Comment by tupoy-ya** [comment]
Old issue, does not seem to happen anymore.
